apiVersion: apps/v1
kind: Deployment
metadata:
  name: evara-frontend-deployment
  labels:
    app: evara-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: evara-frontend
  template:
    metadata:
      labels:
        app: evara-frontend
    spec:
      containers:
      - name: evara-frontend-container
        image: jeevancs/evara-frontend:latest
        ports:
        - containerPort: 80
